ALTER TABLE Colaborador
ADD FOREIGN KEY(cidade) REFERENCES Cidade(nomeCidade)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE Empresa
ADD FOREIGN KEY(cidade) REFERENCES Cidade(nomeCidade)
ON UPDATE CASCADE
ON DELETE CASCADE;
